# FILE_NAME: configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  app-config.production.yaml: |
{{- if .Values.app.config }}
{{ .Values.app.config | nindent 4 }}
{{- else }}
    app:
      baseUrl: ${APP_BASE_URL}
    backend:
      baseUrl: ${BACKEND_BASE_URL}
      listen: ':7007'
      csp:
        connect-src: ["'self'", 'http:', 'https:']
        frame-src: ["'self'", {{ .Values.config.keycloakFrameSrc | quote }}]
      cors:
        origin: ${APP_BASE_URL}
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: pg
        pluginDivisionMode: schema
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          database: {{ .Values.config.databaseName }}
    auth:
      environment: production
      session:
        secret: ${AUTH_SESSION_SECRET}
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
        oidc:
          production:
            metadataUrl: {{ .Values.config.oidcMetadataUrl | quote }}
            clientId: ${AUTH_OIDC_CLIENT_ID}
            clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
            prompt: auto
            signIn:
              resolvers:
                - resolver: emailLocalPartMatchingUserEntityName
                  dangerouslyAllowSignInWithoutUserInCatalog: true
    catalog:
      locations:
        - type: file
          target: ./examples/entities.yaml
        - type: file
          target: ./examples/template/template.yaml
          rules:
            - allow: [Template]
        - type: file
          target: ./examples/org.yaml
          rules:
            - allow: [User, Group]
        - type: file
          target: ./examples/cluster-labs.yaml
          rules:
            - allow: [Resource]
    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - type: config
          clusters:
            - name: {{ .Values.config.kubernetesCluster.name | quote }}
              title: {{ .Values.config.kubernetesCluster.title | quote }}
              url: {{ .Values.config.kubernetesCluster.url | quote }}
              authProvider: {{ .Values.config.kubernetesCluster.authProvider }}
              skipTLSVerify: {{ .Values.config.kubernetesCluster.skipTLSVerify }}
              skipMetricsLookup: {{ .Values.config.kubernetesCluster.skipMetricsLookup }}
              customResources:
                - group: tekton.dev
                  apiVersion: v1
                  plural: pipelineruns
                - group: tekton.dev
                  apiVersion: v1
                  plural: taskruns
{{- end }}
