{{- if .Values.httpRoute.enabled }}
# FILE_NAME: httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "backstage.httpRouteName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: {{ include "backstage.backendName" . }}
          port: {{ .Values.backend.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /.backstage
      backendRefs:
        - name: {{ include "backstage.backendName" . }}
          port: {{ .Values.backend.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "backstage.frontendName" . }}
          port: {{ .Values.frontend.service.port }}
{{- end }}
