{{- if .Values.registryPullSecret.create }}
{{- $user := .Values.registryPullSecret.username }}
{{- $pass := .Values.registryPullSecret.password }}
{{- $auth := printf "%s:%s" $user $pass | b64enc }}
# FILE_NAME: registry-pullsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registryPullSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        {{ .Values.registryPullSecret.registry | quote }}: {
          "username": {{ $user | quote }},
          "password": {{ $pass | quote }},
          "auth": {{ $auth | quote }}
        }
      }
    }
{{- end }}
