{{- if .Values.sessionSecret.create }}
# FILE_NAME: session-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sessionSecret.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  AUTH_SESSION_SECRET: {{ .Values.sessionSecret.value | quote }}
{{- end }}
